### ISSUE TITLE
Game crashed after dying.

### ISSUE THREAD

**Issue by Romoslayer** [gigaherz/HudCompass#11]
My game crashed instantly after dying, pretty sure optifine is the reason or part of the reason why.
PS: not sure if there's any way for you to "fix" this I guess due to optifine being incompatible with many mods just thought id put this out there, below is the crash log.
[crash-2022-03-20_21.30.05-client.txt](https://github.com/gigaherz/HudCompass/files/8313124/crash-2022-03-20_21.30.05-client.txt)
.

**Comment by gigaherz** [comment]
Hm... just a null pointer exception. Easy fix. I'll look at it after work.

**Comment by gigaherz** [comment]
Actually on second look, it's not "just a null pointer exception".... how the heck is *that* null?

**Comment by Romoslayer** [comment]
No idea, all that happened before the crash occurred was a lightning dragon from ice and fire killed me with its breath and game crashed before I saw the you died screen.

**Comment by Romoslayer** [comment]
Not sure if this is the same crash issue but I ran into another crash, the game didn't create any crash reports all that I have to give you is my latest logs file. I am also not exactly sure how to reproduce this either, kinda happened out of nowhere and kept happening every time I returned to that world.
[latest.log](https://github.com/gigaherz/HudCompass/files/8375546/latest.log)
.

**Comment by gigaherz** [comment]
> java.lang.NullPointerException
>	at com.mojang.blaze3d.matrix.MatrixStack.func_227860_a_(MatrixStack.java:66)
>	at dev.gigaherz.hudcompass.client.HudOverlay.drawPoi(HudOverlay.java:311)

It appears to be the same crash. I don't know how something can possibly be null. It just makes no sense unless some mod is messing with the MatrixStack object.
I can't fix this. It's not a matter of having a null-check in my mod.
All I can possibly do is add some try/catch and hope for the best, but that feels ugly as fuck. This code shouldn't crash. The way it's written it CANNOT crash.

**Comment by Romoslayer** [comment]
There is a high probability of the crash being caused by another mod since I have many other mods installed. Let me know if you need anything else from my end, I can also link the mod pack if you want to do any more digging.

**Comment by gigaherz** [comment]
Well normally I'd suggest removing stuff like optifine and optimization mods, and seeing if it still happens, and if so, doing some bisecting to find a smaller set of mods you can still reproduce the issue with.
But if it happens so rarely, it's not something I can possibly expect you to do.

**Comment by Romoslayer** [comment]
Yeah normally if I knew how to reproduce the crash I would start to dig through and have a look for myself, which is a problem in this case since I am not sure what conditions need to be met in order to reproduce the crash as it seems to happen randomly and once it happens it continuously happens every time I rejoin the world occurred on. Probably the best bet would be to start digging through mods the next time it happens and see if removing any mods will stop the instant crash on world join.

**Comment by Romoslayer** [comment]
Alright just crashed again I will begin directing and get back to you on anything I find

**Comment by Romoslayer** [comment]
I have narrowed it down to these mods, Journey map is not one of them I just left it in there in case waypoints aided in reproducing the crash. I will also include the world in case you have issues reproducing the crash yourself.

Forge version 1.16.5-36.2.20
![Capture](https://user-images.githubusercontent.com/47157784/160739501-7ce6f7d5-2c1f-49bc-a0e0-8ccba8ce1b8b.PNG)
World file:
https://drive.google.com/drive/folders/1P9eWSUIMJ9Z2YNiSVVi8hZ2Nm1rb6ooe?usp=sharing

**Comment by Romoslayer** [comment]
I believe a recent update from one of those mods is what is causing the crash as I tried going back to a previous version of HuD Compass and the game still crashed the same way.

**Comment by gigaherz** [comment]
I have tried the mods you listed, in my development environment, without optifine (because it doesn't work in dev), and I couldn't cause it to crash. Not even with the save you provided.

![image](https://user-images.githubusercontent.com/685851/161403657-530d8062-3792-4c8f-a91e-b73c4f9542bc.png)

**Comment by Romoslayer** [comment]
Interesting... maybe something happened to the mod files, I will do some more testing.

**Comment by Romoslayer** [comment]
So now HuD Compass 1.16.5-0.5.0 doesn't seem to want to work anymore. I launch Minecraft with Journey map and HuD Compass in the mods folder game loads in I go to a single player world and the compass doesn't show up at all.

Logs:
[latest.log](https://github.com/gigaherz/HudCompass/files/8467768/latest.log)
